names = ["Tran", "Nhat", "Han"]
print(f"Hi {names[0]}! Will you go to my house to have dinner tomorrow?")
print(f"Hi {names[1]}! Will you go to my house to have dinner tomorrow?")
print(f"Hi {names[2]}! Will you go to my house to have dinner tomorrow?")
print("I've just found a bigger table.")
names.insert(0, "Nang")
names.insert(2, "Hana")
names.append("Em")
print(f"Hi {names[0]}! Would you have dinner at my house tomorrow?")
print(f"Hi {names[1]}! Would you have dinner at my house tomorrow?")
print(f"Hi {names[2]}! Would you have dinner at my house tomorrow?")
print(f"Hi {names[3]}! Would you have dinner at my house tomorrow?")
print(f"Hi {names[4]}! Would you have dinner at my house tomorrow?")
print(f"Hi {names[5]}! Would you have dinner at my house tomorrow?")